---

- name: Build CA
  ansible.builtin.command: "make-cadir {{ ca_dir }}"

- name: Copy vars onto target
  ansible.builtin.template:
    src: "vars.j2"
    dest: "{{ ca_dir }}/vars"
    owner: "{{ ca_username }}"
    group: "{{ ca_group }}"
    mode: "u=rwx,g=rw,o=" # 0750
  
- name: Initialize PKI
  ansible.builtin.command: "{{ ca_dir }}/easyrsa init-pki"
  args:
    chdir: "{{ ca_dir }}"

- name: Generate CA with password
  ansible.builtin.command: "{{ ca_dir }}/easyrsa --batch --req-cn=OpenVPN-CA build-ca"
  args:
    chdir: "{{ ca_dir }}"
  environment:
    EASYRSA_BATCH: "1"
    EASYRSA_PASSIN: "pass:{{ ca_password }}"
    EASYRSA_PASSOUT: "pass:{{ ca_password }}"

- name: Set permissions
  ansible.builtin.file:
    path: "{{ ca_dir }}"
    owner: "{{ ca_username }}"
    group: "{{ ca_group }}"
    mode: "u=rwx,g=rx,o=" #0750
    recurse: yes